### ISSUE TITLE
Issue with M2.4.1

### ISSUE THREAD

**Issue by cytracon** [yireo/magento2-replace-inventory#10]
I get the following error after installing your extension:
The contents from the "/xxx/vendor/magento/module-inventory-api/etc/module.xml" file can't be read. Warning!file_get_contents(/xxx/vendor/magento/module-inventory-api/etc/module.xml): failed to open stream: No such file or directory
Somehow it's still looking for the replaced code?

**Comment by jissereitsma** [comment]
Could you outline the exact commands that you ran for installing this? For instance, did you make sure to flush the cache, remove the `vendor` and `composer.lock`, rerun, etcetera. If you are doubting the precise instructions, see here: https://github.com/yireo/magento2-replace-tools

Please note that this is NOT an extension. It is not a Magento module, it does not involve any Magento code. It is a composer hack.

**Comment by jissereitsma** [comment]
I'm closing this issue because of lack of contact.
