### ISSUE TITLE
How restore list module in replace ???

### ISSUE THREAD

**Issue by goben2489** [yireo/magento2-replace-inventory#11]
i remove module via command:
`composer remove yireo/magento2-replace-inventory`
But list module inventory not come back, how reinstall them ?

`"replace": {
    "magento/inventory-composer-installer":"*",
    "magento/inventory-composer-metapackage":"*",
    "magento/module-inventory": "*",
    "magento/module-inventory-admin-ui": "*",
    "magento/module-inventory-advanced-checkout": "*",
    "magento/module-inventory-requisition-list": "*",
    "magento/module-inventory-api": "*",
    "magento/module-inventory-bundle-import-export": "*",
    "magento/module-inventory-bundle-product": "*",
    "magento/module-inventory-bundle-product-indexer": "*",
    "magento/module-inventory-bundle-product-admin-ui": "*",
    "magento/module-inventory-cache": "*",
    "magento/module-inventory-catalog": "*",
    "magento/module-inventory-catalog-admin-ui": "*",
    "magento/module-inventory-catalog-api": "*",
    "magento/module-inventory-catalog-search": "*",
    "magento/module-inventory-configurable-product": "*",
    "magento/module-inventory-configurable-product-admin-ui": "*",
    "magento/module-inventory-configurable-product-indexer": "*",
    "magento/module-inventory-configuration": "*",
    "magento/module-inventory-configuration-api": "*",
    "magento/module-inventory-distance-based-source-selection": "*",
    "magento/module-inventory-distance-based-source-selection-admin-ui": "*",
    "magento/module-inventory-distance-based-source-selection-api": "*",
    "magento/module-inventory-export-stock": "*",
    "magento/module-inventory-export-stock-api": "*",
    "magento/module-inventory-elasticsearch": "*",
    "magento/module-inventory-graph-ql": "*",
    "magento/module-inventory-grouped-product": "*",
    "magento/module-inventory-grouped-product-admin-ui": "*",
    "magento/module-inventory-grouped-product-indexer": "*",
    "magento/module-inventory-import-export": "*",
    "magento/module-inventory-indexer": "*",
    "magento/module-inventory-in-store-pickup": "*",
    "magento/module-inventory-in-store-pickup-admin-ui": "*",
    "magento/module-inventory-in-store-pickup-api": "*",
    "magento/module-inventory-in-store-pickup-frontend": "*",
    "magento/module-inventory-in-store-pickup-graph-ql": "*",
    "magento/module-inventory-in-store-pickup-multishipping": "*",
    "magento/module-inventory-in-store-pickup-quote": "*",
    "magento/module-inventory-in-store-pickup-quote-graph-ql": "*",
    "magento/module-inventory-in-store-pickup-sales": "*",
    "magento/module-inventory-in-store-pickup-sales-admin-ui": "*",
    "magento/module-inventory-in-store-pickup-sales-api": "*",
    "magento/module-inventory-in-store-pickup-shipping": "*",
    "magento/module-inventory-in-store-pickup-shipping-admin-ui": "*",
    "magento/module-inventory-in-store-pickup-shipping-api": "*",
    "magento/module-inventory-in-store-pickup-webapi-extension": "*",
    "magento/module-inventory-low-quantity-notification": "*",
    "magento/module-inventory-low-quantity-notification-admin-ui": "*",
    "magento/module-inventory-low-quantity-notification-api": "*",
    "magento/module-inventory-multi-dimensional-indexer-api": "*",
    "magento/module-inventory-product-alert": "*",
    "magento/module-inventory-reservations": "*",
    "magento/module-inventory-reservations-api": "*",
    "magento/module-inventory-reservation-cli": "*",
    "magento/module-inventory-sales": "*",
    "magento/module-inventory-sales-admin-ui": "*",
    "magento/module-inventory-sales-api": "*",
    "magento/module-inventory-sales-frontend-ui": "*",
    "magento/module-inventory-setup-fixture-generator": "*",
    "magento/module-inventory-shipping": "*",
    "magento/module-inventory-shipping-admin-ui": "*",
    "magento/module-inventory-source-deduction-api": "*",
    "magento/module-inventory-source-selection": "*",
    "magento/module-inventory-source-selection-api": "*"
  }
`

**Comment by jissereitsma** [comment]
Did you try to edit the `composer.json` file manually? Then remove `vendor/`. Then remove `composer.lock`. Note that this is also the troubleshooting tip number 1 mentioned in the docs.

**Comment by Fairlight60** [comment]
I just encountered this too and even if I `composer remove` the Yireo module, it stayed in composer.lock as a dependency because it is marked as a replacement for the Magento MSI modules (which it shouldn't be IMHO, it should just disable the MSI modules and not remove them altogether).  I had to do a `composer remove`, delete the composer.lock and, **most importantly, do a `composer clearcache` before doing a `composer update`**.

**Comment by jissereitsma** [comment]
@Fairlight60 Thanks for commenting. 

I think that either the ticket is no longer irrelevant or it is already covered enough by the hints given. So I will close the current ticket. Feel free to reopen if an issue is still there.
