### ISSUE TITLE
M2.4.3 issue

### ISSUE THREAD

**Issue by mlavelas** [yireo/magento2-replace-inventory#16]
There is a dependency installed by Magento:
magento/project-community-edition  2.4.3  requires  ampersand/magento2-disable-stock-reservation (^1.0)

And this extension requires Magento\InventorySourceDeductionApi\Model\SourceDeductionServiceInterface

So is not possible to place an order at least with bank transfer payment.
After replace this extension, I'm able to place an order.

**Comment by mlavelas** [comment]
Not a requirement of Magento 2.4.3

**Comment by jissereitsma** [comment]
@mlavelas Thanks for addressing this. Indeed this seems like a dependency issue, making it impossible to use the general replacements of this repo. Perhaps you can copy the replacements to your own global composer file and replace only some? Also, does the `ampersand/magento2-disable-stock-reservation` module include a dep with inventory, as it should?

**Comment by jissereitsma** [comment]
Unfortunately, it does not: https://github.com/AmpersandHQ/magento2-disable-stock-reservation/blob/master/composer.json#L6 So perhaps this needs to be reported as a bug with AmpersandHQ. They could use my Yireo ExtensionChecker to list dependencies for adding to composer and `module.xml` :)

**Comment by mlavelas** [comment]
Finally we are going to leave MSI installed for another reasons, but with the ampersand extension to allow stock decrease on order placement.
Thank you for your fast reply :)
