### ISSUE TITLE
How can I remove this?

### ISSUE THREAD

**Issue by simonrl** [yireo/magento2-replace-inventory#2]
Sorry, maybe a stupid question.

I installed this module, then noticed that Smile Elasticsuite needs MSI, and I want to add the inventory modules again.

I am running `composer remove yireo/magento2-replace-inventory`

The composer.json file gets updated, but there's still the `vendor/yireo` directory including all files, and thus the inventory modules stay missing. 

Could you point me the direction please?

Thanks

**Comment by simonrl** [comment]
I managed to remove it by adding this in my `composer.json`:

`'replace': {'yireo/magento2-replace-inventory':'*'}`

Still seems a bit weird I have to do this.

**Comment by jissereitsma** [comment]
I don't know what the cause of this could be. If the `vendor/yireo/magento2-replace-inventory` folder was still there, it would prove that the remove-action failed. Anyway, as of yet, the procedure of this `replace` trick often requires you to remove the entire `vendor/` folder and restore it with a `composer install` command.

**Comment by chrisastley** [comment]
I have this same issue, installed fine using the command but I now have to remove it due to a 3rd party dependency and when I run 

`composer remove yireo/magento2-replace-inventory`

It completes successfully with no error and removes from composer.json, but doesn't remove the module or the entry in composer.lock

**Comment by jissereitsma** [comment]
See the docs for this as well. The replacements are requiring you to deal with composer a different way. If the `composer.lock` file doesn't reflect the right changes, I would simply throw away the `composer.lock` file and rebuild it. This is the burden of using these replacements that are undocumented in the composer project.

**Comment by chrisastley** [comment]
Hi,

Strangely when I remove
`yireo/magento2-replace-content-staging`

this works as expected, but also can't remove the sample-data one.

**Comment by jissereitsma** [comment]
I know it's crazy. The internals of why regular commands sometimes work and sometimes don't is a mystery (I almost wrote misery) to me as well. But bottom-line is, the `composer.json` could be easily updated. But the `composer.lock` often needs rebuilding from scratch.
