### ISSUE TITLE
Two inventory dependencies remaining

### ISSUE THREAD

**Issue by rikwillems** [yireo/magento2-replace-inventory#3]
Hi!

After using yireo/magento2-replace-inventory I see have installed:
* magento/inventory-composer-installer
* magento/inventory-composer-metapackage

Should these be replaced too?

**Comment by jissereitsma** [comment]
No, not really. With which Magento version did you encounter this?

**Comment by rikwillems** [comment]
Version 2.3.3
Although these packages don't do anything by themselves they could also be removed.

**Comment by jissereitsma** [comment]
Ok, they have now been added to the 2.3.3 branch, so this should now be working. I'm closing the ticket, but if this does not work for you, please re-open.
