### ISSUE TITLE
Issue during setup:di:compile with fresh 2.3.4 install

### ISSUE THREAD

**Issue by danbuchal** [yireo/magento2-replace-inventory#4]
After a clean 2.3.4 install, composer require is successfully executed:
`composer require yireo/magento2-replace-inventory:2.3.4`

Immediately after, `setup:di:compile` is run:
```
[magento@myserver magento]$ bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 1 min 385.0 MiB
Generated code and dependency injection configuration successfully.

In ClassReader.php line 26:

  Class Magento\InventoryDistanceBasedSourceSelection\Console\Command\ImportGeoNamesCommand does not exist
```

**Comment by jissereitsma** [comment]
It makes sense that the reported class is missing: You have purposefully removed the package containing that class: https://github.com/yireo/magento2-replace-inventory/blob/magento-2.3.4/composer.json#L27

Did you make sure to remove the `generated/` folder?

**Comment by danbuchal** [comment]
Thank you. I believe clearing the generated folder was definitely the cause.

**Comment by jissereitsma** [comment]
:)
