### ISSUE TITLE
Add support for Magento 2.3.5-p1

### ISSUE THREAD

**Issue by ikk0** [yireo/magento2-replace-inventory#6]
Hey,

big fan of your "replace"-packages.

Are there any plans to add support for 2.3.5-p1? Right now, it seems the packages (also of your other replace packages) can only be used with 2.3.5, but 2.3.5 is buggy and 2.3.5-p1 is the one that people will want to use. :)

Thank you!

Example:

```
    - Installation request for yireo/magento2-replace-bundled 2.3.5 -> satisfiable by yireo/magento2-replace-bundled[2.3.5].
    - yireo/magento2-replace-bundled 2.3.5 requires magento/product-community-edition 2.3.5 -> satisfiable by magento/product-community-edition[2.3.5] but these conflict with your requirements or minimum-stability.
```

composer.json:

```
    "require": {
        "magento/product-community-edition": "2.3.5-p1",
        "yireo/magento2-replace-bundled": "2.3.5",
```

**Comment by jissereitsma** [comment]
As of yet, I have tried the replace packages actually with 2.3.5-p1 without issues. So maybe it is only the messup of Magento with their versioning that is causing issues? https://github.com/yireo/magento2-replace-inventory/commit/15826b2a62b61aaa4690a36884a9049e548a70f6 If you could try from the `magento-2.3.5` branch, then later, a new release `2.3.5` could be run as well.

**Comment by ikk0** [comment]
That did the trick, thank you! composer update works fine now. If you could do this for the other replace packages as well, that'd be very much appreciated. Have a great day!
